import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { type Invoice } from './store';

export const generateInvoicePDF = (invoice: Invoice) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header Color
    doc.setFillColor(15, 23, 42); // Slate 900
    doc.rect(0, 0, pageWidth, 50, 'F');

    // Logo / Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('InvoiceIQ', 15, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Smart Web3 Invoicing Terminal', 15, 32);

    // Invoice Info (Top Right)
    doc.setFontSize(14);
    doc.text(`INVOICE: ${invoice.id}`, pageWidth - 15, 25, { align: 'right' });
    doc.setFontSize(10);
    doc.text(`Dated: ${new Date(invoice.createdAt).toLocaleDateString()}`, pageWidth - 15, 32, { align: 'right' });

    // Client/Project Info
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(12);
    doc.text('BILL TO:', 15, 65);
    doc.setFont('helvetica', 'bold');
    doc.text(invoice.clientName, 15, 72);
    doc.setFont('helvetica', 'normal');
    if (invoice.clientEmail) doc.text(invoice.clientEmail, 15, 78);
    doc.text(`Project: ${invoice.project}`, 15, 84);

    // Due Date Box
    doc.setFillColor(248, 250, 252);
    doc.rect(pageWidth - 65, 60, 50, 25, 'F');
    doc.setTextColor(71, 85, 105);
    doc.setFontSize(9);
    doc.text('DUE DATE', pageWidth - 55, 70);
    doc.setTextColor(239, 68, 68);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(new Date(invoice.dueDate).toLocaleDateString(), pageWidth - 55, 78);

    // Items Table
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).autoTable({
        startY: 100,
        head: [['Description', 'Qty', 'Rate', 'Total']],
        body: invoice.items.map(item => [
            item.description,
            item.quantity,
            `${item.rate.toLocaleString()} ${invoice.currency}`,
            `${(item.quantity * item.rate).toLocaleString()} ${invoice.currency}`
        ]),
        headStyles: {
            fillColor: [99, 102, 241],
            textColor: 255,
            fontSize: 10,
            fontStyle: 'bold',
            cellPadding: 5
        },
        bodyStyles: {
            fontSize: 10,
            cellPadding: 5
        },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 20, halign: 'center' },
            2: { cellWidth: 40, halign: 'right' },
            3: { cellWidth: 40, halign: 'right' }
        },
        margin: { left: 15, right: 15 }
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY = (doc as any).lastAutoTable.finalY + 10;

    // Total Section
    doc.setFillColor(241, 245, 249);
    doc.rect(pageWidth - 85, finalY, 70, 40, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text('Total Amount:', pageWidth - 75, finalY + 15);

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`${invoice.amount.toLocaleString()} ${invoice.currency}`, pageWidth - 75, finalY + 28);

    // Settlement Info (Web3)
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text('PAYMENT VIA STELLAR', 15, finalY + 15);
    doc.setFontSize(8);
    doc.setFont('courier', 'normal');
    doc.text(`Memo ID: ${invoice.id.replace('INV-', '')}`, 15, finalY + 22);

    if (invoice.status === 'paid') {
        doc.setTextColor(16, 185, 129);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('PAYMENT VERIFIED ✓', 15, finalY + 35);
    } else {
        doc.setTextColor(245, 158, 11);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('PENDING ON-CHAIN SETTLEMENT', 15, finalY + 35);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by InvoiceIQ - Secure Web3 Invoicing Platform', pageWidth / 2, 285, { align: 'center' });

    // Download
    doc.save(`InvoiceIQ_${invoice.id}.pdf`);
};
